name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    name: "Release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10-2021.10'

    - name: Build binary
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE="${{ matrix.type }}"
        cmake --build build
        arm-none-eabi-objcopy -O binary build/gpsdo.elf build/gpsdo.bin
    
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/gpsdo.elf
          build/gpsdo.bin
          LICENSE.md
          README.md